development:
  clients:
    default:
      database: icarusweb-dev
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: icarusweb-dev
      hosts:
        - localhost:27017

production:
  clients:
    default:
      database: icarusweb-prod
      hosts:
        - localhost:27017
